### ISSUE TITLE
Add READ-COMITTED to DB connection

### ISSUE THREAD

**Issue by cristiroma** [eaudeweb/recommended-project#11]
This cannot be added by default to settings.php, however we should add information in this project to remind developers to setup the READ-COMMITTED. The settings.php DB configuration should contain the following line:

```php
$databases['default']['default'] = array (
  'init_commands' => ['isolation' => "SET SESSION tx_isolation='READ-COMMITTED'"],
  ...
);
```

1. Update [patches/append-example.settings.local.php.txt](https://github.com/eaudeweb/recommended-project/blob/9.x/patches/append-example.settings.local.php.txt) - to append the configuration
2. Add a section in the main README.md - Project setup and describe this step

**Comment by cristiroma** [comment]
https://helpdesk.eaudeweb.ro/issues/13422

**Comment by dtabirca** [comment]
added

**Comment by cristiroma** [comment]
Needs patch updated

**Comment by tv889** [comment]
Logged ticket https://helpdesk.eaudeweb.ro/issues/17035
