### ISSUE TITLE
Include by default lightning_media

### ISSUE THREAD

**Issue by cristiroma** [eaudeweb/recommended-project#19]
Andrei recommended to add the lightning media module to all projects - https://www.drupal.org/project/lightning_media

It would be interesting to:

1. Add the module to composer and enable out of the box
2. Create minimum configuration (see module documentation on features)
3. Additional media types deem useful out of the box.

**Comment by tv889** [comment]
Logged a ticket https://helpdesk.eaudeweb.ro/issues/17030
