### ISSUE TITLE
Document the steps to compile the theme

### ISSUE THREAD

**Issue by cristiroma** [eaudeweb/recommended-project#2]
This project is using the edwt theme as front-end theme. The purpose of this ticket is to include a step in the deployment action that compiles the theme as part of building the project. And this information is neither present in the edwt theme readme - https://drupal.org/project/edwt

I think Ion would need to clarify this thing for us to be able to add the compilation commands in the pipeline.

**Comment by joSecret** [comment]
The documentation is described in the "Readme" in the EDWT theme
