### ISSUE TITLE
Add and customise phpcs.xml

### ISSUE THREAD

**Issue by cristiroma** [eaudeweb/recommended-project#24]
We can add and customize phpcs.xml with better defaults for new projects: https://github.com/cmems/marine.copernicus.eu/commit/f7eef5a46bf0f6c3b01b671a65bc5d646edad43a#diff-daa856500eea114bbf034fd35b7600050d965e5d19bb0700885c075747848fd8

**Comment by tv889** [comment]
Added ticket on helpdesk  https://helpdesk.eaudeweb.ro/issues/17025
