### ISSUE TITLE
How to bring enhancements from this template to older projects

### ISSUE THREAD

**Issue by cristiroma** [eaudeweb/recommended-project#9]
The purpose of this ticket is to establish a process which would allow us to bring project updates added to this project to be rolled out to existing projects. For example:

1. Deployment ehnancements
2. WYSISWYG - enhancements 
3. New modules etc.

What I propose here - and I'm open to suggestions and enhancements - is a manual approach - a decision among the product owners to inform themselves of any enhancement added here and decide on a project basis.

**Comment by tv889** [comment]
Logged ticket https://helpdesk.eaudeweb.ro/issues/17038

**Comment by cristiroma** [comment]
I don't think this is feasible.
